<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIcmzQ4X\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIcmzQ4X/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerIcmzQ4X.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerIcmzQ4X\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerIcmzQ4X\appAppKernelProdContainer([
    'container.build_hash' => 'IcmzQ4X',
    'container.build_id' => 'e34aab1c',
    'container.build_time' => 1699869721,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIcmzQ4X');
